### ISSUE TITLE
Find a good to-do list

### ISSUE THREAD

**Issue by maxalbert** [maxalbert/sample_todo_list_and_issue_tracker#1]
S is going to investigate various options. The following ones have been suggested:

- [ ] [Wunderlist](https://www.wunderlist.com/)
- [ ] [Todoist](https://todoist.com/)
- [ ] [Github issue tracker](https://github.com/maxalbert/sample_todo_list_and_issue_tracker/issues/) -- how meta :)
- [ ] Probably lots of others.

Things we need to be able to track:

- Short-term todo items (e.g. for an upcoming report)

- Longer-term open questions / investigations we'd like to do (i.e. things we shouldn't forget but don't have time to act upon right now).

   It would be nice if whatever tool we use supports attaching some sort of information to it (e.g. supportive plots or at least comments on the current status and progress).

- Bugs/chores/feature requests for the code itself.

- Anything else?

**Comment by simontudge** [comment]
Asana
